
# Implementação da parte Kafka
services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
            - 2181:2181
    kafka:
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9092"
        links:
            - zookeeper
        environment: 
            # O IP deve ser o IP da máquina, tem como fazer isso dinamicamente explicado aqui https://kafka.js.org/docs
            KAFKA_ADVERTISED_HOST_NAME: 172.20.32.1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_DELETE_TOPIC_ENABLE: 'true'
            KAFKA_CREATE_TOPICS: 'topic-test:1:1'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            